### DISCUSSION TITLE
Single track book naming

### DISCUSSION THREAD

**Discussion by SenorSmartyPants** [seanap/beets-audible#4] [Show and tell]
I made an item_field to check if the book is a single file/track. If it is, don't put track number in the filename.

```
plugins: inline audible

# Place books in their own folders to be compatible with Booksonic and Audiobookshelf servers
paths:
  # For books that belong to a series
  "albumtype:audiobook series_name::.+ series_position::.+": $albumartist/%ifdef{series_name}/%ifdef{series_position} - $album%aunique{}/$track_and_title
  "albumtype:audiobook series_name::.+": $albumartist/%ifdef{series_name}/$album%aunique{}/$track_and_title
  # Stand-alone books
  "albumtype:audiobook": $albumartist/$album%aunique{}/$track_and_title
  default: $albumartist/$album%aunique{}/$track_and_title

item_fields:
  track_and_title: u'%02i - %s' % (track, title) if tracktotal > 1 else title
```
